version: '3.1'

services:

  # Biotransformer Webservices
  biotransformer:
    build:
      context: .
      dockerfile: Dockerfile
    image: quanted/bt_api
    container_name: biotransformer
    ports:
      - "5002:5002"
